###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################


@url = https://localhost:5001

@imageUrl = https%3A%2F%2Ffirebasestorage.googleapis.com%2Fv0%2Fb%2Ffiscanner-web.appspot.com%2Fo%2Fimages%252FKGt2f0vFUIMKCOWlqpOCFwxbKMF3%252F20210519_161651.jpg%3Falt%3Dmedia%26token%3D0d541407-858e-4486-9e3a-2e945e81d0ce

### Check the Home page
GET {{url}} HTTP/1.1


### Check the ping
GET {{url}}/ping HTTP/1.1


### Check simple post
POST {{url}}/api/ScanForm/upload_and_run?modelId HTTP/1.1
Content-Type: multipart/form-data

{
    "images" :""
}

### Post image stored on external storage
POST {{url}}/api/ScanForm/run_remote?url={{imageUrl}} HTTP/1.1

{

}


### Evaluate form image stored on external storage
GET {{url}}/api/ScanForm/evaluate_form?url={{imageUrl}} HTTP/1.1

