###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################


@url = https://localhost:5001

@imageUrl = your_encoded_image_url

### Check the Home page
GET {{url}} HTTP/1.1


### Check the ping
GET {{url}}/ping HTTP/1.1


### Check simple post
POST {{url}}/api/ScanForm/upload_and_run?modelId HTTP/1.1
Content-Type: multipart/form-data

{
    "images" :""
}

### Post image stored on external storage
POST {{url}}/api/ScanForm/run_remote?url={{imageUrl}} HTTP/1.1

{

}


### Evaluate form image stored on external storage
GET {{url}}/api/ScanForm/evaluate_form?url={{imageUrl}} HTTP/1.1

