###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################

@url = https://localhost:5001

@imageUrl = <<your_encoded_image_url>>
@classifierModelId = <<your_classifier_model_id>>
@recognizerModelId = <<your_recognizer_model_id>>

### Check the Home page
GET {{url}} HTTP/1.1


### Check the ping
GET {{url}}/ping HTTP/1.1



### Bind the Classification model to the Feature Extraction Model
POST {{url}}/Settings/SetupClassificationModel HTTP/1.1
Content-Type: application/json

{
    "key": "{{classifierModelId}}",
    "value": "{{recognizerModelId}}"
}


### Classify the image
POST  {{url}}/ScanForm/Classify HTTP/1.1
Content-Type: application/json

{
    "url": "{{imageUrl}}"
}


### Evaluate 
POST {{url}}/ScanForm/Evaluate HTTP/1.1
Content-Type: application/json

{
    "classificationModelId": "{{classifierModelId}}",
    "url": "{{imageUrl}}"
}


### Classify and Evaluate in one single step
POST {{url}}/ScanForm/ClassifyAndEvaluate HTTP/1.1
Content-Type: application/json

{
    "url": "{{imageUrl}}"
}


### Scan ID document image as public available url
POST {{url}}/ScanUser/IdDocument HTTP/1.1
Content-Type: application/json

{
    "url": "{{imageUrl}}"
}