version: '3.9'

services:
  formrecognizer.webapi:
    image: genocs/formrecognizer-webapi:3.1.0
    build:
      context: .
      dockerfile: webapi.dockerfile

  formrecognizer.worker:
    image: genocs/formrecognizer-worker:1.1.0
    build:
      context: .
      dockerfile: worker.dockerfile
