version: '3.9'

services:
  formrecognizer.webapi:
    image: genocs/formrecognizer-webapi:5.0.4
    hostname: formrecognizer.webapi
    container_name: formrecognizer.webapi
    build:
      context: .
      dockerfile: webapi.dockerfile
    ports:
      - 5200:80
      - 5201:443
    networks:
      - genocs
    volumes:
      - formrecognizer:/var/lib/formrecognizer

  formrecognizer.worker:
    image: genocs/formrecognizer-worker:5.0.4
    hostname: formrecognizer.worker
    container_name: formrecognizer.worker
    networks:
      - genocs    
    build:
      context: .
      dockerfile: worker.dockerfile

networks:
  genocs:
    name: genocs-network
    external: true

volumes:
  formrecognizer:
    driver: local
