name: publish to nuget
on:
  push:
    branches: [master]

jobs:

  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core    
        uses: actions/setup-dotnet@v1
      
      - name: Publish to NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Genocs.Integration.CognitiveServices/Genocs.Integration.CognitiveServices.csproj
          PACKAGE_NAME: Genocs.Integration.CognitiveServices
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
