name: publish to nuget
on:
  push:
    branches: [master]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Package
        run: dotnet pack src/Genocs.Integration.CognitiveServices/Genocs.Integration.CognitiveServices.csproj -c Release
      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate`
        
      # - name: Pack
      #   run: dotnet pack EasyDbMigrator\\EasyDbMigrator.csproj -c Release
      # - name: Publish to GitHub packages
      #  run: dotnet nuget push /home/runner/work/EasyDbMigrator/EasyDbMigrator/EasyDbMigrator/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate`

